version: '3'

services:
  back-end:
    container_name: back-end
    build:
      context: ./back-end
      dockerfile: Dockerfile
    env_file:
      - ./back-end/.env
    environment:
      - GITHUB_PERSONAL_ACCESS_TOKEN=5fe0aa51399edda813603c16de5456e3bfc1df37
    restart: on-failure
    ports:
      - "8080:8080"
    expose:
      - "8080"
    depends_on:
      - db
      - test-db

  front-end:
    container_name: front-end
    build:
      context: ./front-end
      dockerfile: Dockerfile
    env_file:
      - ./front-end/.env
    environment:
      - REACT_APP_API_HOST=192.168.99.100
    restart: on-failure
    ports:
      - "3000:3000"
    expose:
      - "3000"

  db:
    container_name: db
    build:
      context: ./postgresdb
      dockerfile: Dockerfile
    env_file:
      - ./postgresdb/.env
    restart: on-failure
    ports:
      - "5433:5432"
    expose:
      - "5433"
    volumes:
      - db-data:/data/db

  test-db:
    container_name: test-db
    build:
      context: ./postgresdb
      dockerfile: Dockerfile
    env_file:
      - ./postgresdb/.test.env
    restart: on-failure
    ports:
      - "5434:5432"
    expose:
      - "5434"
    volumes:
      - test-db-data:/data/db

volumes:
  db-data:
  test-db-data: