export const LOGIN_REQUESTED = 'LOGIN_REQUESTED';
export const LOGIN_SUCCEEDED = 'LOGIN_SUCCEEDED';
export const RETRIEVE_REPOSITORIES = 'RETRIEVE_REPOSITORIES';
export const RENEW_REPOSITORY = 'RENEW_REPOSITORY';